#!/bin/bash
#
# Whisky - a collection of stateless RNGs
# by Sean Connelly (@velipso), https://sean.cm
# The Unlicense License
# Project Home: https://github.com/velipso/whisky
#

set -e

if ! which dieharder > /dev/null; then
	echo 'Missing dieharder' >&2
	echo 'You must install the dieharder tool to continue' >&2
	exit 1
fi

if ! which clang > /dev/null; then
	echo 'Missing clang' >&2
	echo 'You must install the clang tool to continue' >&2
	exit 1
fi

if [ ! -e test.c ]; then
	echo 'Missing test.c' >&2
	echo 'This script should be ran inside the top-level directory in the whiksy repo' >&2
	exit 1
fi

echo 'Generating whisky.out...'
clang -O2 -o whisky.out test.c

if [ $# -lt 1 ]; then
	echo 'Usage:'
	echo '  ./report <generator>'
	echo ''
	echo 'For a list of generators, run:'
	echo '  ./whisky.out'
	exit 1
fi

if ! ./whisky.out "$1"; then
	echo 'Invalid generator' >&2
	echo ''
	echo 'For a list of generators, run:'
	echo '  ./whisky.out'
	exit 1
fi

DIM=$(echo "$1" | sed 's/^\([0-9]*\).*/\1/g')
AXIS=1
FILE='reports/whisky'"$1"'.txt'
rm -f "$FILE"
while [ "$AXIS" -le "$DIM" ]; do
	for DIRECTION in '+' '-'; do
		echo 'Generating report for' "$1" 'along axis' "$AXIS"'/'"$DIM"', '"$DIRECTION"' direction...'
		echo '###############################################################################' >> "$FILE"
		echo '#' >> "$FILE"
		echo '# whisky'"$1"', axis '"$AXIS"' of '"$DIM"', '"$DIRECTION"' direction' >> "$FILE"
		echo '#' >> "$FILE"
		echo '###############################################################################' >> "$FILE"
		echo '' >> "$FILE"
		./whisky.out "$1" "$AXIS" "$DIRECTION" | dieharder -g 200 -a | tee -a "$FILE"
		echo '' >> "$FILE"
	done
	AXIS=$(( $AXIS + 1 ))
done
